In [43]:
import pandas as pd
import numpy as np

In [44]:
df = pd.read_csv('../Data/Culicidae/dados_tratados_todos_culicidae.csv')
df.head()

,SRA acc,Biosample acc,Bioproject acc,Taxonomia acc,Instrumento,Amostras,Bases,Tamanho,Organismo,Estratégia,Recurso,Seleção,Protocolo,Criação
0,DRR870143,SAMD01750741,PRJDB39421,7159,Illumina HiSeq 4000,25113835,7.5,2748.71,Aedes aegypti,RNA-Seq,Transcriptomic,Random,"Myd88-3-ECCinfection, using Quantseq 3' mRNA-s...",2026/06/01
1,DRR870142,SAMD01750740,PRJDB39421,7159,Illumina HiSeq 4000,24795456,7.4,2700.24,Aedes aegypti,RNA-Seq,Transcriptomic,Random,"Myd88-3, using Quantseq 3' mRNA-seq prep kit",2026/06/01
2,DRR870141,SAMD01750739,PRJDB39421,7159,Illumina HiSeq 4000,22395959,6.7,2426.74,Aedes aegypti,RNA-Seq,Transcriptomic,Random,"Myd88-2-ECCinfection, using Quantseq 3' mRNA-s...",2026/06/01
3,DRR870140,SAMD01750738,PRJDB39421,7159,Illumina HiSeq 4000,24092864,7.2,2642.57,Aedes aegypti,RNA-Seq,Transcriptomic,Random,"Myd88-2, using Quantseq 3' mRNA-seq prep kit",2026/06/01
4,DRR870139,SAMD01750737,PRJDB39421,7159,Illumina HiSeq 4000,23805015,7.1,2607.44,Aedes aegypti,RNA-Seq,Transcriptomic,Random,"Myd88-1-ECCinfection, using Quantseq 3' mRNA-s...",2026/06/01

In [46]:
df_embaralhado = df.sample(frac=1, random_state=42).reset_index(drop=True)
df_embaralhado.head()

,SRA acc,Biosample acc,Bioproject acc,Taxonomia acc,Instrumento,Amostras,Bases,Tamanho,Organismo,Estratégia,Recurso,Seleção,Protocolo,Criação
0,SRR23404227,SAMN33244624,PRJNA933651,7159,Illumina HiSeq 4000,6805283,0.3,130.82,Aedes aegypti,RNA-Seq,Transcriptomic,Cdna,"Afterwards, mosquitoes were dissected into tis...",2024/01/01
1,SRR33623074,SAMN48584689,PRJNA1265117,7159,NextSeq 1000,1736019,0.8,228.52,Aedes aegypti,AMPLICON,Genomic,Pcr,NaN,2025/05/19
2,SRR30649700,SAMN43719550,PRJNA1160270,7175,Illumina MiSeq,1329,0.0,0.45,Culex pipiens,AMPLICON,Genomic,Pcr,NaN,2024/09/13
3,SRR25243046,SAMN36410820,PRJNA993867,7159,Illumina HiSeq 4000,8843755,0.4,153.56,Aedes aegypti,RNA-Seq,Transcriptomic,Random Pcr,NaN,2023/07/12
4,SRR12086973,SAMN15364804,PRJNA641755,7160,Illumina HiSeq 2000,3032616,0.4,706.61,Aedes albopictus,RAD-Seq,Genomic,Pcr,NaN,2020/06/25