In [78]:
import pandas as pd
import numpy as np
import os

In [79]:
# Leitura do dataframe contendo os dados brutos
ORGANISMO = 'Aedes'
df = pd.read_csv(f'../Data/{ORGANISMO}/dados_brutos.csv')
df.head()

/tmp/ipykernel_4672/3549131240.py:3: DtypeWarning: Columns (0: Run_load_done, 1: Run_is_public, 2: Run_static_data_available, 3: Instrument_DNBSEQ, 4: Instrument_ELEMENT, 5: Instrument_ION_TORRENT, 6: Instrument_LS454, 7: Instrument_ABI_SOLID, 8: Statistics_static_data_available) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'../Data/{ORGANISMO}/dados_brutos.csv')

,id,createdate,updatedate,Run_acc,Run_total_spots,Run_total_bases,Run_load_done,Run_is_public,Run_cluster_name,Run_static_data_available,...,Instrument_BGISEQ,Instrument_DNBSEQ,Organism_CommonName,Instrument_PACBIO_SMRT,Instrument_ELEMENT,Instrument_CAPILLARY,Instrument_ION_TORRENT,Instrument_LS454,Instrument_ABI_SOLID,Statistics_static_data_available
0,42083430,2026/06/01,2025/12/16,DRR870143,25113835.0,7.487355e+09,True,True,public,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,42083429,2026/06/01,2025/12/16,DRR870142,24795456.0,7.380453e+09,True,True,public,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,42083428,2026/06/01,2025/12/16,DRR870141,22395959.0,6.673388e+09,True,True,public,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,42083427,2026/06/01,2025/12/16,DRR870140,24092864.0,7.183008e+09,True,True,public,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,42083426,2026/06/01,2025/12/16,DRR870139,23805015.0,7.099766e+09,True,True,public,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [80]:
# Verificando colunas do dataframe
print(df.columns)

Index(['id', 'createdate', 'updatedate', 'Run_acc', 'Run_total_spots',
       'Run_total_bases', 'Run_load_done', 'Run_is_public', 'Run_cluster_name',
       'Run_static_data_available', 'Title', 'Platform',
       'Platform_instrument_model', 'Statistics_total_runs',
       'Statistics_total_spots', 'Statistics_total_bases',
       'Statistics_total_size', 'Statistics_load_done',
       'Statistics_cluster_name', 'LIBRARY_NAME', 'LIBRARY_STRATEGY',
       'LIBRARY_SOURCE', 'LIBRARY_SELECTION', 'LIBRARY_CONSTRUCTION_PROTOCOL',
       'Submitter_acc', 'Submitter_center_name', 'Submitter_contact_name',
       'Submitter_lab_name', 'Experiment_acc', 'Experiment_ver',
       'Experiment_status', 'Experiment_name', 'Study_acc', 'Study_name',
       'Organism_taxid', 'Organism_ScientificName', 'Sample_acc',
       'Sample_name', 'Instrument_ILLUMINA', 'Bioproject', 'Biosample',
       'Instrument_OXFORD_NANOPORE', 'Instrument_BGISEQ', 'Instrument_DNBSEQ',
       'Organism_CommonName', 'Instrument_PACBIO_SMRT', 'Instrument_ELEMENT',
       'Instrument_CAPILLARY', 'Instrument_ION_TORRENT', 'Instrument_LS454',
       'Instrument_ABI_SOLID', 'Statistics_static_data_available'],
      dtype='str')

In [81]:
# Filtrando os dados relevantes
main_df = df[['Run_acc', 
            'Biosample',
            'Bioproject',
            'Organism_taxid',
            'Platform_instrument_model', 
            'Statistics_total_spots', 
            'Statistics_total_bases', 
            'Statistics_total_size',
            'Organism_ScientificName', 
            'LIBRARY_STRATEGY',
            'LIBRARY_SOURCE', 
            'LIBRARY_SELECTION', 
            'LIBRARY_CONSTRUCTION_PROTOCOL', 
            'createdate',
]]
main_df.columns = ['SRA acc', 
                'Biosample acc', 
                'Bioproject acc', 
                'Taxonomia acc', 
                'Instrumento', 
                'Amostras', 
                'Bases', 
                'Tamanho',
                'Organismo',
                'Estratégia',
                'Recurso',
                'Seleção',
                'Protocolo',
                'Criação',
]

main_df.head()

,SRA acc,Biosample acc,Bioproject acc,Taxonomia acc,Instrumento,Amostras,Bases,Tamanho,Organismo,Estratégia,Recurso,Seleção,Protocolo,Criação
0,DRR870143,SAMD01750741,PRJDB39421,7159,Illumina HiSeq 4000,25113835,7487355449,2748713976,Aedes aegypti,RNA-Seq,TRANSCRIPTOMIC,RANDOM,"Myd88-3-ECCinfection, using Quantseq 3' mRNA-s...",2026/06/01
1,DRR870142,SAMD01750740,PRJDB39421,7159,Illumina HiSeq 4000,24795456,7380452801,2700238205,Aedes aegypti,RNA-Seq,TRANSCRIPTOMIC,RANDOM,"Myd88-3, using Quantseq 3' mRNA-seq prep kit",2026/06/01
2,DRR870141,SAMD01750739,PRJDB39421,7159,Illumina HiSeq 4000,22395959,6673387621,2426738963,Aedes aegypti,RNA-Seq,TRANSCRIPTOMIC,RANDOM,"Myd88-2-ECCinfection, using Quantseq 3' mRNA-s...",2026/06/01
3,DRR870140,SAMD01750738,PRJDB39421,7159,Illumina HiSeq 4000,24092864,7183008156,2642565060,Aedes aegypti,RNA-Seq,TRANSCRIPTOMIC,RANDOM,"Myd88-2, using Quantseq 3' mRNA-seq prep kit",2026/06/01
4,DRR870139,SAMD01750737,PRJDB39421,7159,Illumina HiSeq 4000,23805015,7099766031,2607439844,Aedes aegypti,RNA-Seq,TRANSCRIPTOMIC,RANDOM,"Myd88-1-ECCinfection, using Quantseq 3' mRNA-s...",2026/06/01

In [82]:
# Ajustando tipos não recomendados
main_df['Tamanho'] = main_df['Tamanho'].astype(np.float32)
main_df['Bases'] = main_df['Bases'].astype(np.float32)
main_df['Taxonomia acc'] = main_df['Taxonomia acc'].astype(str)

# Avaliando strings mal formatadas
main_df['Recurso'] = main_df['Recurso'].str.title()
main_df['Seleção'] = main_df['Seleção'].str.title()

# Ajustando dados numéricos
main_df['Tamanho'] = main_df['Tamanho'].apply(lambda x: round(x / 1e6, 2))
main_df['Bases'] = main_df['Bases'].apply(lambda x: round(x / 1e9, 1))

In [83]:
# Verificando novo estado
main_df.head()

,SRA acc,Biosample acc,Bioproject acc,Taxonomia acc,Instrumento,Amostras,Bases,Tamanho,Organismo,Estratégia,Recurso,Seleção,Protocolo,Criação
0,DRR870143,SAMD01750741,PRJDB39421,7159,Illumina HiSeq 4000,25113835,7.5,2748.71,Aedes aegypti,RNA-Seq,Transcriptomic,Random,"Myd88-3-ECCinfection, using Quantseq 3' mRNA-s...",2026/06/01
1,DRR870142,SAMD01750740,PRJDB39421,7159,Illumina HiSeq 4000,24795456,7.4,2700.24,Aedes aegypti,RNA-Seq,Transcriptomic,Random,"Myd88-3, using Quantseq 3' mRNA-seq prep kit",2026/06/01
2,DRR870141,SAMD01750739,PRJDB39421,7159,Illumina HiSeq 4000,22395959,6.7,2426.74,Aedes aegypti,RNA-Seq,Transcriptomic,Random,"Myd88-2-ECCinfection, using Quantseq 3' mRNA-s...",2026/06/01
3,DRR870140,SAMD01750738,PRJDB39421,7159,Illumina HiSeq 4000,24092864,7.2,2642.57,Aedes aegypti,RNA-Seq,Transcriptomic,Random,"Myd88-2, using Quantseq 3' mRNA-seq prep kit",2026/06/01
4,DRR870139,SAMD01750737,PRJDB39421,7159,Illumina HiSeq 4000,23805015,7.1,2607.44,Aedes aegypti,RNA-Seq,Transcriptomic,Random,"Myd88-1-ECCinfection, using Quantseq 3' mRNA-s...",2026/06/01

In [84]:
diretorio = f'../Data/{ORGANISMO}'

os.makedirs(f'{diretorio}', exist_ok = True)
main_df.to_csv(f'{diretorio}/dados_tratados_{ORGANISMO}.csv', index = False)

In [85]:
main_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 29965 entries, 0 to 29964
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   SRA acc         29964 non-null  str
 1   Biosample acc   29965 non-null  str
 2   Bioproject acc  29529 non-null  str
 3   Taxonomia acc   29965 non-null  str
 4   Instrumento     29965 non-null  str
 5   Amostras        29965 non-null  int64
 6   Bases           29965 non-null  float64
 7   Tamanho         29965 non-null  float64
 8   Organismo       29421 non-null  str
 9   Estratégia      29965 non-null  str
 10  Recurso         29965 non-null  str
 11  Seleção         29965 non-null  str
 12  Protocolo       1667 non-null   str
 13  Criação         29965 non-null  str
dtypes: float64(2), int64(1), str(11)
memory usage: 3.2 MB